kind: ConfigMap
apiVersion: v1
metadata:
  name: standup-configmap
data:
  NODE_ENV: "production"
  GITHUB_ORGANIZATION: "SocialGouv"
  MATOMO_SITE_ID: "58"
  MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
