apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: www-sealed-secret
  namespace: transition-collective
spec:
  encryptedData:
    SENTRY_DSN: >-
      AgCWgMegcd1JLm+AqV24Rv8jMl/T9ri8ZWY6RoF0TjCADZPaHNiLFA+UA60q0BGMTqyePuvTjmz3TafbPozH5I52PIhKICv/SaXOFr4c+MnTiW+WELqjT8LhelVBj1+nx+IQftDjrdWAxDSgvEzlQv9gb8Pz8ONe5tUoEgmDxJJYDVuGxZ1n9ONNFLotVcWVtoDfNhj7NwL8E6hBPqN+ga83fdT6MzuIeCL/b/gJymqCJswdegFmdEAn3BkHfL7djlDDTroahkmWFcNWdcrc0rX/lJD+9GUJlZXAAGf6Xy+kr2RDYY/U4+dlJKCpPuhmxgaX0GPYIElAJ/ap5aiFUKN/bExLJajERLMkdYWVOVnSozYw1wBfBVLJvD5YampAxAovFmOFv2F2grtonsg+twnjJNcyezjnuXSAlYHgH5Z8IHVcsITidi7YU0SwWPziXM+XYHlwh7Kr+A8tITbPCvEhDkahoT4ZnPnGlj3LLlpcZEnDJ+U5Tekam8ZzsegsDON0MNlZ+LXzquMZjt3tQiH8Dcu6QVSiEPFNH5OrL09Wh2xO5bYH25yu5ksY7PHmUFZllC698E6CbC4hCSPHRR+9ETxD4KZfiHuRrytfJ2WJnOc7f31+QziZqVv2JGRCEE8GZXyQdvY6jKHlnwVl7KFuSvJf5YlZs/RiRY2TrEomI46nk4xMYQq536jY+gfGqUsdAw68
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: www-sealed-secret
    type: Opaque
