apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: {}
  name: www-sealed-secret
  namespace: transitions-collectives
spec:
  encryptedData:
    SENTRY_DSN: >-
      AgApBrbRkqAEeHMkFFrMRCV1zZClAVHnhNZ5YNxuwy0svJHk0xacv6QnFrs/xgrIISEM8P8ksHVzXvM38WCIhI+JHIX7TvxtFt58aOTBDpsjWCKiB/wiMYPw3DPHjlyijV1z+8JirUKYRHT3vr9tbo8oNUOspRHYRCUD5yvxD3MkHT5v8+egFBi4htPJqPDJHSMiVydxG99B8WKMaFH51JOZ4iJ9ShzKS1aazpQ/HZ8tmrv9HCwrI5KlnqugyV2QHIMzm7qfaiIxpmYyX0DSCMM1/x4UVim7kJ+U8ecRk6eCvES6e1D4EaIWsQBgJ9LffCmqls0vjNc1Oc10LVjj1SiXLXYrs71iFMjf0Y6Gv7tkc89kcj20FQQjP0q8/ge9IO6ps09YDfH0I1i1jm3hFlJLulgUgd4hPnxHYlRtqs+g6h21Ieojwp6QO128JiBjo9XvS9jL2UMGY+KLm4VHdoypfoqKsTJnqPlZVIdADGqavIE88Z+CjwWJ7HXjQcMKn/2uIznXrwwIw+9Znc8u8APjwLsf0vu7HhQyLYjR4tcCXrvpDL5iTwAXtlz6sp40PDL24z1FiZ2tpGupbvnulA3T3eu2hBJf+V4Wg/CzQCCAfh+VM/Je6VwUjU/PNS4kvsXbW0THV6xP/LpmsW8ewPqT/MY+BG4z0o1WdYt6zPzQEuD/SbmibXdqwK7AG7al7Omsy2E5OmOuTZztt1RDdLpy9kai1HY9uDRWhN+8HEQLIn2yJ5eTEFXQ2hAg0lLNyHK/tDseLC4JFeYFqPkeyR5kNgcuUIXFrpBgvQ==
  template:
    metadata:
      annotations: {}
      name: www-sealed-secret
    type: Opaque
